const mongoose = require("mongoose");

//define a comment schema for the database
const InfoSchema = new mongoose.Schema({
  creator_id: String,
  name: String,
  email: String,
  location: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
});

// compile model from schema
module.exports = mongoose.model("information", InfoSchema);
