const mongoose = require("mongoose");

//define a memory schema for the database
const MemorySchema = new mongoose.Schema({
  creator_id: String,
  creator_name: String,
  parent: String, // links to the _id of a parent theme (_id is an autogenerated field by Mongoose).
  content: {
      type: Map,
      of: String
  },
});

// compile model from schema
module.exports = mongoose.model("memory", MemorySchema);